version: '2'

services:

  svc-example:
    build: ..
    image: quay.io/guidesmiths/svc-example:latest
    links:
     - mongo:mongo
     - redis:redis
     - vault:vault
     - postgres:postgres

  mongo:
    image: mongo

  redis:
    image: redis

  postgres:
    image: postgres

  vault:
    image: sjourdan/vault
    hostname: vault
